security:
    sessions: never
spring:
    jackson:
        joda-date-time-format: yyyy-MM-dd HH:mm:ss
        date-format: yyyy-MM-dd HH:mm:ss
        serialization:
            write_dates_as_timestamps: true
    mvc:
        favicon:
            enabled: false

#
#mybatis:
#    type-aliases-package: com.qianyi
#    type-handlers-package: com.qianyi
#    configuration:
#        map-underscore-to-camel-case: true
#        default-fetch-size: 100
#        default-statement-timeout: 30